# Generated by Django 5.2.17 on 2026-09-23 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64, verbose_name='отчёт')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'XLSX'), ('csv', 'CSV')], max_length=8, verbose_name='формат')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='параметры')),
                ('file', models.FileField(blank=True, upload_to='reports/%Y/%m/', verbose_name='файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'отчёт',
                'verbose_name_plural': 'отчёты',
                'ordering': ('-created_at',),
                'permissions': [('export_report', 'Выгружать отчёты')],
            },
        ),
    ]
