# Generated by Django 5.2.17 on 2026-09-23 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('normalization', '0001_initial'),
        ('topology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('external_id', models.BigIntegerField(unique=True, verbose_name='ид_канала_данных')),
                ('tag', models.CharField(blank=True, max_length=128, verbose_name='тег инженерной системы')),
                ('name', models.CharField(max_length=255, verbose_name='название датчика')),
                ('picket', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='пикет')),
                ('location_hint', models.CharField(blank=True, max_length=64, verbose_name='место (ВШ, камера…)')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('in_catalog', models.BooleanField(default=True, help_text='False — канал встречен в журнале, но отсутствует в справочнике заказчика', verbose_name='есть в справочнике')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='topology.node', verbose_name='объект')),
                ('profile_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='normalization.sensorprofile', verbose_name='индивидуальный профиль')),
            ],
            options={
                'verbose_name': 'канал данных',
                'verbose_name_plural': 'каналы данных',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('kind', models.CharField(choices=[('hatch', 'Люк'), ('vent_shaft', 'Вентшахта'), ('chamber', 'Камера'), ('pump', 'Насос'), ('fan', 'Вентилятор'), ('ups', 'ИБП'), ('cabinet', 'Шкаф автоматики'), ('sensor', 'Датчик')], max_length=16, verbose_name='вид')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('inventory_number', models.CharField(blank=True, max_length=64, verbose_name='инвентарный номер')),
                ('picket', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='пикет')),
                ('commissioned_at', models.DateField(blank=True, null=True, verbose_name='ввод в эксплуатацию')),
                ('last_maintenance_at', models.DateField(blank=True, null=True, verbose_name='последнее ТО')),
                ('maintenance_interval_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='регламентный интервал ТО, дн')),
                ('mtbf_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='средняя наработка на отказ, ч')),
                ('source', models.CharField(choices=[('emulated', 'эмуляция'), ('imported', 'импорт'), ('manual', 'вручную')], default='emulated', max_length=16, verbose_name='источник записи')),
                ('channels', models.ManyToManyField(blank=True, related_name='equipment', to='assets.channel', verbose_name='каналы')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='topology.node', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'единица оборудования',
                'verbose_name_plural': 'реестр оборудования',
            },
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='тип датчика')),
                ('system_type', models.CharField(blank=True, max_length=128, verbose_name='инженерная подсистема')),
                ('domain', models.CharField(choices=[('fire', 'Пожар'), ('gas', 'Загазованность'), ('flood', 'Подтопление'), ('intrusion', 'Несанкционированный доступ'), ('power', 'Электропитание'), ('process', 'Технологическое оборудование'), ('climate', 'Микроклимат')], max_length=16, verbose_name='направление риска')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_types', to='normalization.sensorprofile', verbose_name='профиль нормализации')),
            ],
            options={
                'verbose_name': 'тип датчика',
                'verbose_name_plural': 'типы датчиков',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='sensor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='assets.sensortype', verbose_name='тип датчика'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['node', 'sensor_type'], name='assets_chan_node_id_34fc14_idx'),
        ),
    ]
