# Generated by Django 5.2.17 on 2026-09-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='kind',
            field=models.CharField(choices=[('hatch', 'Люк'), ('door', 'Дверь / аварийный выход'), ('vent_shaft', 'Вентшахта'), ('chamber', 'Камера'), ('pump', 'Насос'), ('fan', 'Вентилятор'), ('ups', 'ИБП'), ('cabinet', 'Шкаф автоматики'), ('sensor', 'Датчик')], max_length=16, verbose_name='вид'),
        ),
    ]
