# Generated by Django 5.2.17 on 2026-09-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_equipment_door'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='location',
            field=models.JSONField(blank=True, null=True, verbose_name='точка на карте'),
        ),
    ]
