# Generated by Django 5.2.17 on 2026-09-27 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_channel_location'),
        ('topology', '0003_alter_node_options_node_adjacent_node_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('external_id', models.CharField(max_length=64, unique=True, verbose_name='ид камеры в системе видеонаблюдения')),
                ('picket', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='пикет')),
                ('location', models.JSONField(blank=True, null=True, verbose_name='точка на карте')),
                ('is_active', models.BooleanField(default=True, verbose_name='работает')),
            ],
            options={
                'verbose_name': 'камера видеонаблюдения',
                'verbose_name_plural': 'камеры видеонаблюдения',
                'ordering': ('node', 'picket', 'name'),
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='condition',
            field=models.CharField(blank=True, choices=[('good', 'Исправно'), ('remarks', 'Работоспособно, есть замечания'), ('needs_repair', 'Требует ремонта'), ('faulty', 'Неисправно')], max_length=16, verbose_name='фактическое состояние'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='condition_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='состояние на'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False — списано или выведено', verbose_name='в эксплуатации'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='синхронизировано с реестром'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='source',
            field=models.CharField(choices=[('emulated', 'эмуляция'), ('imported', 'реестр заказчика'), ('manual', 'вручную')], default='emulated', max_length=16, verbose_name='источник записи'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['inventory_number'], name='assets_equi_invento_669f15_idx'),
        ),
        migrations.AddField(
            model_name='camera',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='topology.node', verbose_name='объект'),
        ),
    ]
