# Generated by Django 5.2.17 on 2026-09-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_camera_equipment_condition_equipment_condition_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='количество'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='system',
            field=models.CharField(blank=True, max_length=32, verbose_name='система'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='type_name',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='вид по регламенту ТО'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='unit',
            field=models.CharField(default='шт.', max_length=16, verbose_name='ед. изм.'),
        ),
    ]
