# Generated by Django 5.2.17 on 2026-09-28 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_equipment_quantity_equipment_system_and_more'),
        ('topology', '0004_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='topology.floor', verbose_name='этаж'),
        ),
    ]
