# Generated by Django 5.2.17 on 2026-09-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('external_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ид_объект во внешней системе')),
                ('kind', models.CharField(choices=[('district', 'Район по эксплуатации'), ('complex', 'Объект (комплекс)'), ('control_house', 'Диспетчерский пункт / шкаф'), ('guard_object', 'Охраняемый объект'), ('section', 'Участок коллектора')], max_length=32, verbose_name='вид')),
                ('source_kind', models.CharField(blank=True, max_length=64, verbose_name='вид_объекта в источнике')),
                ('name', models.CharField(max_length=255, verbose_name='диспетчерское название')),
                ('picket_from', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='пикет от')),
                ('picket_to', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='пикет до')),
                ('geometry', models.JSONField(blank=True, null=True, verbose_name='геометрия (GeoJSON, схематическая)')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'узел топологии',
                'verbose_name_plural': 'топология объектов',
            },
        ),
    ]
