# Generated by Django 5.2.17 on 2026-09-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0002_node_criticality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'permissions': [('manage_zones', 'Создаёт и меняет зоны ответственности, их границы и смежность')], 'verbose_name': 'узел топологии', 'verbose_name_plural': 'топология объектов'},
        ),
        migrations.AddField(
            model_name='node',
            name='adjacent',
            field=models.ManyToManyField(blank=True, to='topology.node', verbose_name='смежные зоны'),
        ),
        migrations.AddField(
            model_name='node',
            name='color',
            field=models.CharField(blank=True, max_length=16, verbose_name='цвет зоны'),
        ),
        migrations.AddField(
            model_name='node',
            name='geometry_source',
            field=models.CharField(blank=True, max_length=64, verbose_name='источник контура'),
        ),
        migrations.AlterField(
            model_name='node',
            name='geometry',
            field=models.JSONField(blank=True, null=True, verbose_name='контур на карте (GeoJSON, WGS84)'),
        ),
        migrations.AlterField(
            model_name='node',
            name='kind',
            field=models.CharField(choices=[('district', 'Район по эксплуатации'), ('zone', 'Зона ответственности'), ('complex', 'Объект (комплекс)'), ('control_house', 'Диспетчерский пункт / шкаф'), ('guard_object', 'Охраняемый объект'), ('section', 'Участок коллектора')], max_length=32, verbose_name='вид'),
        ),
    ]
