# Generated by Django 5.2.17 on 2026-09-28 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0003_alter_node_options_node_adjacent_node_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(help_text='0 — цокольный, отрицательные — подземные', verbose_name='этаж')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='название')),
                ('is_base', models.BooleanField(default=False, verbose_name='контрольный этаж')),
                ('plan', models.FileField(blank=True, upload_to='plans/%Y/%m/', verbose_name='план помещений')),
                ('plan_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='ширина плана, px')),
                ('plan_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='высота плана, px')),
                ('points', models.JSONField(blank=True, default=list, verbose_name='контрольные точки')),
                ('corners', models.JSONField(blank=True, null=True, verbose_name='углы плана на местности')),
                ('rmse_m', models.FloatField(blank=True, null=True, verbose_name='невязка привязки, м')),
                ('opacity', models.FloatField(default=0.85, verbose_name='прозрачность плана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='topology.node', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'этаж',
                'verbose_name_plural': 'этажи',
                'ordering': ('node', 'level'),
                'constraints': [models.UniqueConstraint(fields=('node', 'level'), name='floor_unique_level')],
            },
        ),
    ]
