# Generated by Django 5.2.17 on 2026-09-26 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='раздел')),
                ('slug', models.SlugField(unique=True, verbose_name='код')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'раздел вики',
                'verbose_name_plural': 'разделы вики',
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='адрес')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='кратко')),
                ('body', models.TextField(verbose_name='текст (Markdown)')),
                ('roles', models.JSONField(blank=True, default=list, verbose_name='для ролей')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликована')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='кто изменил')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='wiki.wikisection', verbose_name='раздел')),
            ],
            options={
                'verbose_name': 'статья вики',
                'verbose_name_plural': 'статьи вики',
                'ordering': ('section__order', 'order', 'title'),
            },
        ),
    ]
