# Generated by Django 5.2.17 on 2026-09-23 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facet', models.CharField(default='primary', max_length=32, verbose_name='аспект')),
                ('state', models.CharField(choices=[('normal', 'normal'), ('warning', 'warning'), ('alarm', 'alarm'), ('fault', 'fault'), ('power_loss', 'power_loss'), ('unknown', 'unknown'), ('event', 'event')], max_length=16, verbose_name='состояние')),
                ('numeric', models.FloatField(blank=True, null=True, verbose_name='числовое значение')),
                ('raw_value', models.CharField(blank=True, max_length=255, verbose_name='сырое значение')),
                ('changed_at', models.DateTimeField(verbose_name='состояние с')),
                ('last_seen_at', models.DateTimeField(db_index=True, verbose_name='последнее сообщение')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='assets.channel')),
            ],
            options={
                'verbose_name': 'состояние канала',
                'verbose_name_plural': 'состояния каналов',
                'constraints': [models.UniqueConstraint(fields=('channel', 'facet'), name='uniq_channel_facet')],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('pk', models.CompositePrimaryKey('ts', 'event_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(verbose_name='время')),
                ('event_id', models.BigIntegerField(verbose_name='ид_события')),
                ('raw_value', models.CharField(blank=True, max_length=255, verbose_name='сырое значение')),
                ('raw_alarm', models.BooleanField(null=True, verbose_name='тревожное (по источнику)')),
                ('numeric', models.FloatField(null=True, verbose_name='числовое значение')),
                ('state', models.CharField(choices=[('normal', 'normal'), ('warning', 'warning'), ('alarm', 'alarm'), ('fault', 'fault'), ('power_loss', 'power_loss'), ('unknown', 'unknown'), ('event', 'event')], max_length=16, verbose_name='состояние')),
                ('facet', models.CharField(default='primary', max_length=32, verbose_name='аспект')),
                ('quality', models.CharField(choices=[('ok', 'ok'), ('empty', 'empty'), ('epoch_artifact', 'epoch_artifact'), ('sentinel', 'sentinel'), ('out_of_range', 'out_of_range'), ('unexpected_numeric', 'unexpected_numeric'), ('unmapped_text', 'unmapped_text')], default='ok', max_length=24, verbose_name='качество')),
                ('channel', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.channel', verbose_name='канал')),
            ],
            options={
                'verbose_name': 'показание',
                'verbose_name_plural': 'показания',
                'indexes': [models.Index(fields=['channel', '-ts'], name='reading_channel_ts')],
            },
        ),
    ]
