# Generated by Django 5.2.17 on 2026-09-24 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('telemetry', '0002_timescale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelDaily',
            fields=[
                ('pk', models.CompositePrimaryKey('day', 'channel', blank=True, editable=False, primary_key=True, serialize=False)),
                ('day', models.DateField(verbose_name='сутки')),
                ('readings', models.PositiveIntegerField(verbose_name='показаний')),
                ('normal', models.PositiveIntegerField(default=0, verbose_name='норма')),
                ('warnings', models.PositiveIntegerField(default=0, verbose_name='предупреждений')),
                ('alarms', models.PositiveIntegerField(default=0, verbose_name='тревог')),
                ('faults', models.PositiveIntegerField(default=0, verbose_name='неисправностей')),
                ('power_losses', models.PositiveIntegerField(default=0, verbose_name='потерь питания')),
                ('unknowns', models.PositiveIntegerField(default=0, verbose_name='неопределённых')),
                ('events', models.PositiveIntegerField(default=0, verbose_name='рабочих событий')),
                ('invalid', models.PositiveIntegerField(default=0, verbose_name='невалидных значений')),
                ('numeric_avg', models.FloatField(null=True, verbose_name='среднее')),
                ('numeric_min', models.FloatField(null=True, verbose_name='минимум')),
                ('numeric_max', models.FloatField(null=True, verbose_name='максимум')),
                ('first_ts', models.DateTimeField(verbose_name='первое сообщение')),
                ('last_ts', models.DateTimeField(verbose_name='последнее сообщение')),
                ('channel', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.channel', verbose_name='канал')),
            ],
            options={
                'verbose_name': 'суточная сводка канала',
                'verbose_name_plural': 'суточные сводки каналов',
                'indexes': [models.Index(fields=['channel', '-day'], name='channeldaily_channel_day')],
            },
        ),
    ]
