# Generated by Django 5.2.17 on 2026-09-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_channeldaily_hypertable'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeldaily',
            name='first_fault_ts',
            field=models.DateTimeField(blank=True, null=True, verbose_name='первая неисправность за сутки'),
        ),
        migrations.AddField(
            model_name='channeldaily',
            name='last_state',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='состояние на конец суток'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='quality',
            field=models.CharField(choices=[('ok', 'ok'), ('empty', 'empty'), ('epoch_artifact', 'epoch_artifact'), ('sentinel', 'sentinel'), ('out_of_range', 'out_of_range'), ('drift', 'drift'), ('unexpected_numeric', 'unexpected_numeric'), ('unmapped_text', 'unmapped_text')], default='ok', max_length=24, verbose_name='качество'),
        ),
    ]
