# Generated by Django 5.2.17 on 2026-09-23 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='время')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='логин')),
                ('action', models.CharField(db_index=True, max_length=64, verbose_name='действие')),
                ('method', models.CharField(blank=True, max_length=8, verbose_name='метод')),
                ('path', models.CharField(blank=True, max_length=512, verbose_name='путь')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='код ответа')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='объект')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='детали')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'действие пользователя',
                'verbose_name_plural': 'журнал действий',
                'ordering': ('-ts',),
            },
        ),
    ]
