# Generated by Django 5.2.17 on 2026-09-24 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='ид объекта'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='object_type',
            field=models.CharField(blank=True, max_length=64, verbose_name='тип объекта'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['object_type', 'object_id', 'ts'], name='audit_actio_object__e4ad95_idx'),
        ),
    ]
