# Generated by Django 5.2.17 on 2026-09-25 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topology', '0002_node_criticality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=64, verbose_name='урок')),
                ('role', models.CharField(blank=True, max_length=32, verbose_name='роль')),
                ('status', models.CharField(choices=[('active', 'Идёт'), ('done', 'Пройдено'), ('abandoned', 'Прервано')], default='active', max_length=16, verbose_name='статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='завершено')),
                ('steps', models.JSONField(blank=True, default=dict, verbose_name='выполненные шаги')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='контекст')),
                ('hints', models.PositiveSmallIntegerField(default=0, verbose_name='подсказок')),
                ('mistakes', models.PositiveSmallIntegerField(default=0, verbose_name='ошибок')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='topology.node', verbose_name='объект полигона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training', to=settings.AUTH_USER_MODEL, verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'учебное задание',
                'verbose_name_plural': 'учебные задания',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='training_tr_user_id_fbdeea_idx')],
            },
        ),
    ]
