# Generated by Django 5.2.17 on 2026-09-26 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0002_node_criticality'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('scenario', models.CharField(max_length=32, verbose_name='сценарий')),
                ('speed', models.FloatField(default=2.0, verbose_name='темп нарастания')),
                ('complication', models.CharField(blank=True, max_length=32, verbose_name='осложнение')),
                ('complication_after_min', models.PositiveSmallIntegerField(default=3, verbose_name='осложнение через, мин')),
                ('duration_min', models.PositiveSmallIntegerField(default=30, verbose_name='длительность, мин')),
                ('briefing', models.TextField(blank=True, verbose_name='вводная для участников')),
                ('status', models.CharField(choices=[('scheduled', 'Назначены'), ('running', 'Идут'), ('finished', 'Завершены'), ('stopped', 'Прекращены досрочно'), ('cancelled', 'Отменены')], db_index=True, default='scheduled', max_length=16, verbose_name='статус')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='начало по таймеру')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='начались')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='закончились')),
                ('stop_reason', models.CharField(blank=True, max_length=255, verbose_name='причина прекращения')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='контекст')),
                ('report', models.JSONField(blank=True, default=dict, verbose_name='разбор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='руководитель')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='topology.node', verbose_name='объект полигона')),
                ('stopped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='прекратил')),
            ],
            options={
                'verbose_name': 'учения',
                'verbose_name_plural': 'учения',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExerciseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=32, verbose_name='роль')),
                ('silent', models.BooleanField(default=False, verbose_name='молчащий (проверка эскалации)')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='оповещён')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='ознакомлен')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='training.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL, verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'участник учений',
                'verbose_name_plural': 'участники учений',
                'unique_together': {('exercise', 'user')},
            },
        ),
    ]
