# Generated by Django 5.2.17 on 2026-09-23 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('forecasting', '0001_initial'),
        ('topology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('outcome', models.CharField(choices=[('brigade_dispatched', 'Выезд бригады'), ('check_requested', 'Направлена проверка'), ('monitoring', 'Мониторинг ситуации'), ('false_alarm', 'Ложное срабатывание'), ('confirmed', 'Инцидент подтверждён'), ('resolved', 'Устранено')], max_length=32, verbose_name='вид решения')),
                ('incident_types', models.JSONField(blank=True, default=list, verbose_name='применимо к типам')),
            ],
            options={
                'verbose_name': 'причина решения',
                'verbose_name_plural': 'справочник причин решений',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EscalationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('severity', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], max_length=16, unique=True, verbose_name='уровень')),
                ('ack_timeout_minutes', models.PositiveIntegerField(verbose_name='время на реакцию, мин')),
                ('max_level', models.PositiveSmallIntegerField(default=3, verbose_name='макс. уровней эскалации')),
                ('repeat_notify_minutes', models.PositiveIntegerField(default=5, verbose_name='повтор уведомления, мин')),
            ],
            options={
                'verbose_name': 'политика эскалации',
                'verbose_name_plural': 'политики эскалации',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('type', models.CharField(choices=[('sensor_failure', 'Отказ датчика'), ('fire', 'Пожар / задымление'), ('gas', 'Загазованность'), ('flood', 'Подтопление'), ('intrusion', 'Несанкционированный доступ'), ('power', 'Потеря питания'), ('equipment', 'Отказ оборудования')], db_index=True, max_length=32, verbose_name='тип')),
                ('severity', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], db_index=True, max_length=16, verbose_name='уровень')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('acknowledged', 'Принят'), ('in_progress', 'В работе'), ('resolved', 'Решён'), ('closed', 'Закрыт')], db_index=True, default='new', max_length=16, verbose_name='статус')),
                ('is_forecast', models.BooleanField(default=False, help_text='Предупреждение о риске, а не факт', verbose_name='прогнозный')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('probability', models.FloatField(blank=True, null=True, verbose_name='вероятность')),
                ('horizon_hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='горизонт, ч')),
                ('opened_at', models.DateTimeField(db_index=True, verbose_name='открыт')),
                ('ack_deadline', models.DateTimeField(blank=True, null=True, verbose_name='реакция до')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='принят')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='решён')),
                ('escalation_level', models.PositiveSmallIntegerField(default=0, verbose_name='уровень эскалации')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL, verbose_name='в работе у')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='topology.node', verbose_name='объект')),
                ('responsible_node', models.ForeignKey(help_text='Узел вертикали, который сейчас отвечает за реакцию; поднимается при эскалации', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='topology.node', verbose_name='ответственный уровень')),
            ],
            options={
                'verbose_name': 'инцидент',
                'verbose_name_plural': 'инциденты',
                'ordering': ('-opened_at',),
                'permissions': [('decide_incident', 'Принимать решение по инциденту'), ('escalate_incident', 'Эскалировать инцидент'), ('takeover_incident', 'Забирать инцидент у другого диспетчера')],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('brigade_dispatched', 'Выезд бригады'), ('check_requested', 'Направлена проверка'), ('monitoring', 'Мониторинг ситуации'), ('false_alarm', 'Ложное срабатывание'), ('confirmed', 'Инцидент подтверждён'), ('resolved', 'Устранено')], max_length=32, verbose_name='решение')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('decided_at', models.DateTimeField(auto_now_add=True, verbose_name='когда')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='кто')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='incidents.decisionreason', verbose_name='причина')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='incidents.incident', verbose_name='инцидент')),
            ],
            options={
                'verbose_name': 'решение',
                'verbose_name_plural': 'решения',
                'ordering': ('-decided_at',),
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('forecast', 'Прогноз'), ('rule', 'Правило'), ('manual', 'Вручную'), ('external', 'Внешняя система')], max_length=16, verbose_name='источник')),
                ('type', models.CharField(choices=[('sensor_failure', 'Отказ датчика'), ('fire', 'Пожар / задымление'), ('gas', 'Загазованность'), ('flood', 'Подтопление'), ('intrusion', 'Несанкционированный доступ'), ('power', 'Потеря питания'), ('equipment', 'Отказ оборудования')], max_length=32, verbose_name='тип')),
                ('severity', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], max_length=16, verbose_name='уровень')),
                ('raised_at', models.DateTimeField(db_index=True, verbose_name='время')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='детали')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='квитирован')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='assets.channel', verbose_name='канал')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='topology.node', verbose_name='объект')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='forecasting.prediction', verbose_name='прогноз')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='incidents.incident', verbose_name='инцидент')),
            ],
            options={
                'verbose_name': 'алерт',
                'verbose_name_plural': 'алерты',
                'ordering': ('-raised_at',),
                'permissions': [('acknowledge_alert', 'Квитировать алерты')],
            },
        ),
        migrations.CreateModel(
            name='IncidentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('opened', 'Открыт'), ('alert_attached', 'Добавлен сигнал'), ('acknowledged', 'Принят'), ('assigned', 'Взят в работу'), ('released', 'Освобождён'), ('escalated', 'Эскалирован'), ('decision', 'Решение'), ('workorder', 'Заявка'), ('status', 'Смена статуса'), ('comment', 'Комментарий')], max_length=16)),
                ('text', models.CharField(blank=True, max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='incidents.incident')),
            ],
            options={
                'ordering': ('ts',),
            },
        ),
    ]
