# Generated by Django 5.2.17 on 2026-09-24 14:12

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Существующие карточки: контур по типу, счётчики и границы эпизода — по их алертам."""
    from django.db.models import Count, Max, Min

    Incident = apps.get_model("incidents", "Incident")
    physical = {"fire", "gas", "flood", "intrusion"}
    for incident in Incident.objects.annotate(
        n=Count("alerts"), ch=Count("alerts__channel", distinct=True), first=Min("alerts__raised_at"), last=Max("alerts__raised_at")
    ):
        incident.contour = "physical" if incident.type in physical else "technical"
        incident.signals_count, incident.channels_count = incident.n, incident.ch
        incident.first_signal_at = incident.first or incident.opened_at
        incident.last_signal_at = incident.last or incident.opened_at
        incident.save(update_fields=["contour", "signals_count", "channels_count", "first_signal_at", "last_signal_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_alert_type_alter_incident_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='actions',
            field=models.JSONField(blank=True, default=list, verbose_name='следующие действия'),
        ),
        migrations.AddField(
            model_name='incident',
            name='channels_count',
            field=models.PositiveIntegerField(default=0, verbose_name='каналов'),
        ),
        migrations.AddField(
            model_name='incident',
            name='contour',
            field=models.CharField(choices=[('physical', 'Физический'), ('technical', 'Технический')], db_index=True, default='technical', max_length=16, verbose_name='контур риска'),
        ),
        migrations.AddField(
            model_name='incident',
            name='data_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='уверенность данных (средний балл)'),
        ),
        migrations.AddField(
            model_name='incident',
            name='first_signal_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='первый сигнал'),
        ),
        migrations.AddField(
            model_name='incident',
            name='hypotheses',
            field=models.JSONField(blank=True, default=list, verbose_name='гипотезы первопричины'),
        ),
        migrations.AddField(
            model_name='incident',
            name='last_signal_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='последний сигнал'),
        ),
        migrations.AddField(
            model_name='incident',
            name='priority',
            field=models.FloatField(db_index=True, default=0, verbose_name='операционный приоритет'),
        ),
        migrations.AddField(
            model_name='incident',
            name='priority_factors',
            field=models.JSONField(blank=True, default=dict, verbose_name='составляющие приоритета'),
        ),
        migrations.AddField(
            model_name='incident',
            name='signals_count',
            field=models.PositiveIntegerField(default=0, verbose_name='сигналов'),
        ),
        migrations.AlterField(
            model_name='incidentevent',
            name='kind',
            field=models.CharField(choices=[('opened', 'Открыт'), ('alert_attached', 'Добавлен сигнал'), ('type_changed', 'Уточнён тип'), ('action_done', 'Выполнен шаг'), ('acknowledged', 'Принят'), ('assigned', 'Взят в работу'), ('released', 'Освобождён'), ('escalated', 'Эскалирован'), ('decision', 'Решение'), ('workorder', 'Заявка'), ('status', 'Смена статуса'), ('comment', 'Комментарий')], max_length=16),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
