# Generated by Django 5.2.17 on 2026-09-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='cause',
            field=models.CharField(blank=True, choices=[('sensor_fault', 'Неисправность датчика'), ('communication', 'Потеря связи'), ('power', 'Обесточивание'), ('false_alarm', 'Ложное срабатывание'), ('external', 'Внешнее воздействие'), ('works', 'Работы на объекте'), ('real_event', 'Реальное событие'), ('insufficient_data', 'Недостаточно данных')], max_length=32, verbose_name='что произошло'),
        ),
        migrations.AddField(
            model_name='decision',
            name='forecast_useful',
            field=models.BooleanField(blank=True, null=True, verbose_name='прогноз помог'),
        ),
    ]
