# Generated by Django 5.2.17 on 2026-09-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_decision_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_emulated',
            field=models.BooleanField(db_index=True, default=False, verbose_name='эмуляция'),
        ),
    ]
