# Generated by Django 5.2.17 on 2026-09-25 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill(apps, schema_editor):
    from apps.incidents.first import backfill as run

    run(
        apps.get_model("incidents", "Incident"),
        apps.get_model("audit", "ActionLog"),
        apps.get_model("incidents", "IncidentEvent"),
        apps.get_model("incidents", "Decision"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_incident_emulated'),
        ('audit', '0002_object_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # отметки для уже существующих карточек — по журналу просмотров и хронологии
        migrations.AddField(
            model_name='incident',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='заметил в'),
        ),
        migrations.AddField(
            model_name='incident',
            name='first_seen_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='первым заметил'),
        ),
        migrations.AddField(
            model_name='incident',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='откликнулся в'),
        ),
        migrations.AddField(
            model_name='incident',
            name='responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='первым откликнулся'),
        ),
            migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
