# Generated by Django 5.2.17 on 2026-09-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_first_responder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentevent',
            name='kind',
            field=models.CharField(choices=[('opened', 'Открыт'), ('alert_attached', 'Добавлен сигнал'), ('type_changed', 'Уточнён тип'), ('action_done', 'Выполнен шаг'), ('acknowledged', 'Принят'), ('assigned', 'Взят в работу'), ('released', 'Освобождён'), ('escalated', 'Эскалирован'), ('decision', 'Решение'), ('workorder', 'Заявка'), ('status', 'Смена статуса'), ('comment', 'Комментарий'), ('video_check', 'Проверка по камерам')], max_length=16),
        ),
    ]
