# Generated by Django 5.2.17 on 2026-09-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_alter_incidentevent_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('sensor_failure', 'Отказ датчика'), ('fire', 'Пожар / задымление'), ('gas', 'Загазованность'), ('flood', 'Подтопление'), ('intrusion', 'Несанкционированный доступ'), ('temperature', 'Аномальная температура'), ('power', 'Потеря питания'), ('equipment', 'Отказ оборудования'), ('communication', 'Потеря связи')], max_length=32, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('sensor_failure', 'Отказ датчика'), ('fire', 'Пожар / задымление'), ('gas', 'Загазованность'), ('flood', 'Подтопление'), ('intrusion', 'Несанкционированный доступ'), ('temperature', 'Аномальная температура'), ('power', 'Потеря питания'), ('equipment', 'Отказ оборудования'), ('communication', 'Потеря связи')], db_index=True, max_length=32, verbose_name='тип'),
        ),
    ]
