# Generated by Django 5.2.17 on 2026-09-24 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('topology', '0002_node_criticality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='совпадает с departmentNumber в LDAP', max_length=64, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('kind', models.CharField(choices=[('management', 'Руководство'), ('ods', 'Объединённая диспетчерская служба'), ('unit', 'Диспетчерская подразделения'), ('brigade', 'Ремонтная бригада'), ('analytics', 'Аналитическая группа'), ('support', 'Администрирование и смежные службы')], max_length=16, verbose_name='вид')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='руководитель')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.team', verbose_name='вышестоящая команда')),
                ('scope_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='topology.node', verbose_name='зона ответственности')),
            ],
            options={
                'verbose_name': 'команда',
                'verbose_name_plural': 'команды',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.team', verbose_name='команда'),
        ),
    ]
