# Generated by Django 5.2.17 on 2026-09-26 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_team'),
        ('topology', '0003_alter_node_options_node_adjacent_node_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_all_scopes', 'Видит все зоны ответственности'), ('assign_staff', 'Назначает сотрудников в зоны и командирует в другие зоны')], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.CreateModel(
            name='Secondment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='с')),
                ('ends_at', models.DateTimeField(verbose_name='по')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='причина')),
                ('emergency', models.BooleanField(default=False, verbose_name='крайний случай (зона не смежная)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='отозван')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='кто направил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondments', to=settings.AUTH_USER_MODEL, verbose_name='сотрудник')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondments', to='topology.node', verbose_name='куда направлен')),
            ],
            options={
                'verbose_name': 'командирование в другую зону',
                'verbose_name_plural': 'командирования в другие зоны',
                'ordering': ('-starts_at',),
                'indexes': [models.Index(fields=['user', 'ends_at'], name='accounts_se_user_id_0520fc_idx')],
            },
        ),
    ]
