# Generated by Django 5.2.17 on 2026-09-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_secondment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_all_scopes', 'Видит все зоны ответственности'), ('assign_staff', 'Назначает сотрудников в зоны и командирует в другие зоны'), ('view_grafana', 'Аналитические панели Grafana'), ('view_system_monitoring', 'Мониторинг системы: Prometheus и системные панели Grafana')], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='team',
            name='kind',
            field=models.CharField(choices=[('management', 'Руководство'), ('ods', 'Объединённая диспетчерская служба'), ('unit', 'Диспетчерская подразделения'), ('brigade', 'Ремонтная бригада'), ('maintenance', 'Служба технического обслуживания'), ('analytics', 'Аналитическая группа'), ('support', 'Администрирование и смежные службы')], max_length=16, verbose_name='вид'),
        ),
    ]
