# Generated by Django 5.2.17 on 2026-09-23 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('topology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('task', models.CharField(choices=[('sensor_failure', 'Отказ датчика'), ('gas', 'Загазованность'), ('flood', 'Подтопление'), ('fire', 'Пожар'), ('intrusion', 'Несанкционированный доступ')], max_length=32, unique=True, verbose_name='задача')),
                ('medium_threshold', models.FloatField(default=0.3, verbose_name='порог «средний»')),
                ('high_threshold', models.FloatField(default=0.6, verbose_name='порог «высокий»')),
                ('critical_threshold', models.FloatField(default=0.85, verbose_name='порог «критический»')),
                ('alert_from_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='high', max_length=16, verbose_name='создавать алерт от уровня')),
                ('horizon_hours', models.PositiveSmallIntegerField(default=24, verbose_name='горизонт прогноза, ч')),
                ('enabled', models.BooleanField(default=True, verbose_name='включено')),
            ],
            options={
                'verbose_name': 'политика риска',
                'verbose_name_plural': 'политики риска',
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('task', models.CharField(choices=[('sensor_failure', 'Отказ датчика'), ('gas', 'Загазованность'), ('flood', 'Подтопление'), ('fire', 'Пожар'), ('intrusion', 'Несанкционированный доступ')], max_length=32, verbose_name='задача')),
                ('version', models.CharField(max_length=32, verbose_name='версия')),
                ('algorithm', models.CharField(default='lightgbm', max_length=64, verbose_name='алгоритм')),
                ('horizon_hours', models.PositiveSmallIntegerField(default=24, verbose_name='горизонт, ч')),
                ('status', models.CharField(choices=[('training', 'Обучается'), ('ready', 'Готова'), ('active', 'Активна'), ('archived', 'В архиве'), ('failed', 'Ошибка')], default='training', max_length=16, verbose_name='статус')),
                ('artifact_path', models.CharField(blank=True, max_length=512, verbose_name='артефакт')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='признаки')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='гиперпараметры')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='метрики на валидации')),
                ('train_period', models.JSONField(blank=True, default=dict, verbose_name='период обучения')),
                ('notes', models.TextField(blank=True, verbose_name='методика / комментарий')),
            ],
            options={
                'verbose_name': 'модель',
                'verbose_name_plural': 'реестр моделей',
                'permissions': [('retrain_model', 'Запускать дообучение моделей')],
                'constraints': [models.UniqueConstraint(fields=('task', 'version'), name='uniq_model_version'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('task',), name='one_active_model_per_task')],
            },
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('task', models.CharField(choices=[('sensor_failure', 'Отказ датчика'), ('gas', 'Загазованность'), ('flood', 'Подтопление'), ('fire', 'Пожар'), ('intrusion', 'Несанкционированный доступ')], max_length=32, verbose_name='задача')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Выполняется'), ('done', 'Завершён'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='статус')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='параметры')),
                ('log', models.TextField(blank=True, verbose_name='журнал')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='завершён')),
                ('result_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecasting.mlmodel', verbose_name='результат')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'запуск обучения',
                'verbose_name_plural': 'запуски обучения',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('sensor_failure', 'Отказ датчика'), ('gas', 'Загазованность'), ('flood', 'Подтопление'), ('fire', 'Пожар'), ('intrusion', 'Несанкционированный доступ')], db_index=True, max_length=32, verbose_name='задача')),
                ('issued_at', models.DateTimeField(db_index=True, verbose_name='сформирован')),
                ('horizon_hours', models.PositiveSmallIntegerField(verbose_name='горизонт, ч')),
                ('valid_until', models.DateTimeField(verbose_name='действует до')),
                ('probability', models.FloatField(verbose_name='вероятность')),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], db_index=True, max_length=16, verbose_name='уровень риска')),
                ('factors', models.JSONField(blank=True, default=list, verbose_name='факторы риска')),
                ('summary', models.TextField(blank=True, verbose_name='пояснение')),
                ('outcome', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтвердился'), ('not_confirmed', 'Не подтвердился'), ('prevented', 'Предотвращён')], default='pending', max_length=16, verbose_name='результат')),
                ('outcome_at', models.DateTimeField(blank=True, null=True, verbose_name='результат зафиксирован')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='assets.channel', verbose_name='канал')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecasting.mlmodel', verbose_name='модель')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='topology.node', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'прогноз',
                'verbose_name_plural': 'журнал прогнозов',
                'ordering': ('-issued_at',),
                'indexes': [models.Index(fields=['task', 'risk_level', '-issued_at'], name='forecasting_task_722940_idx')],
            },
        ),
    ]
