# Generated by Django 5.2.17 on 2026-09-24 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_equipment_door'),
        ('forecasting', '0001_initial'),
        ('topology', '0002_node_criticality'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelHealth',
            fields=[
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='health', serialize=False, to='assets.channel')),
                ('computed_at', models.DateTimeField(verbose_name='рассчитан')),
                ('score', models.PositiveSmallIntegerField(db_index=True, verbose_name='балл')),
                ('components', models.JSONField(default=dict, verbose_name='составляющие')),
                ('periodic', models.BooleanField(default=False, verbose_name='периодический канал')),
                ('expected_interval_s', models.PositiveIntegerField(blank=True, null=True, verbose_name='ожидаемый интервал, с')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='последнее сообщение')),
                ('silent', models.BooleanField(db_index=True, default=False, verbose_name='молчит')),
                ('silent_since', models.DateTimeField(blank=True, null=True, verbose_name='молчит с')),
            ],
            options={
                'verbose_name': 'качество данных канала',
                'verbose_name_plural': 'качество данных каналов',
            },
        ),
        migrations.CreateModel(
            name='ChannelRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('sensor_failure', 'Отказ датчика'), ('gas', 'Загазованность'), ('flood', 'Подтопление'), ('fire', 'Пожар'), ('intrusion', 'Несанкционированный доступ')], max_length=32, verbose_name='задача')),
                ('as_of', models.DateTimeField(verbose_name='на момент')),
                ('probability', models.FloatField(verbose_name='вероятность')),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], db_index=True, max_length=16, verbose_name='уровень риска')),
                ('factors', models.JSONField(blank=True, default=list, verbose_name='факторы риска')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='assets.channel')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecasting.mlmodel', verbose_name='модель')),
            ],
            options={
                'verbose_name': 'риск канала',
                'verbose_name_plural': 'риски каналов',
                'constraints': [models.UniqueConstraint(fields=('channel', 'task'), name='uniq_channel_risk')],
            },
        ),
        migrations.CreateModel(
            name='RiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('sensor_failure', 'Отказ датчика'), ('gas', 'Загазованность'), ('flood', 'Подтопление'), ('fire', 'Пожар'), ('intrusion', 'Несанкционированный доступ')], max_length=32, verbose_name='задача')),
                ('as_of', models.DateTimeField(db_index=True, verbose_name='на момент')),
                ('max_probability', models.FloatField(verbose_name='максимальная вероятность по каналам')),
                ('expected_failures', models.FloatField(verbose_name='ожидаемое число отказов за горизонт')),
                ('channels_total', models.PositiveIntegerField(verbose_name='каналов оценено')),
                ('channels_at_risk', models.PositiveIntegerField(verbose_name='каналов с риском от среднего')),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], max_length=16, verbose_name='уровень риска')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_snapshots', to='topology.node')),
            ],
            options={
                'verbose_name': 'снимок риска объекта',
                'verbose_name_plural': 'снимки риска объектов',
                'ordering': ('-as_of',),
                'indexes': [models.Index(fields=['node', 'task', '-as_of'], name='forecasting_node_id_d034d5_idx')],
            },
        ),
    ]
