# Generated by Django 5.2.17 on 2026-09-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0002_channelhealth_channelrisk_risksnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrun',
            name='progress',
            field=models.FloatField(default=0, verbose_name='прогресс, %'),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='stage',
            field=models.CharField(blank=True, max_length=128, verbose_name='этап'),
        ),
    ]
