# Generated by Django 5.2.17 on 2026-09-24 12:25

from django.db import migrations, models


def dedupe(apps, schema_editor):
    """Повторные циклы на один момент времени оставляли дубли снимков — оставляем последний."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "DELETE FROM forecasting_risksnapshot a USING forecasting_risksnapshot b "
        "WHERE a.node_id = b.node_id AND a.task = b.task AND a.as_of = b.as_of AND a.id < b.id"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0004_prediction_backtest'),
        ('topology', '0002_node_criticality'),
    ]

    operations = [
        migrations.RunPython(dedupe, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='risksnapshot',
            constraint=models.UniqueConstraint(fields=('node', 'task', 'as_of'), name='uniq_risk_snapshot'),
        ),
    ]
