# Generated by Django 5.2.17 on 2026-09-24 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_equipment_door'),
        ('forecasting', '0005_risksnapshot_unique'),
        ('incidents', '0003_episode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='код причины')),
                ('title', models.CharField(max_length=255, verbose_name='причина')),
                ('effect', models.CharField(choices=[('positive', 'Подтверждает отказ датчика'), ('negative', 'Не отказ датчика'), ('exclude', 'Исключить из обучения'), ('ignore', 'Не влияет на обучение')], max_length=16, verbose_name='эффект для обучения')),
                ('weight', models.FloatField(default=1.0, help_text='во сколько раз пример важнее обычного', verbose_name='вес метки')),
                ('auto_accept', models.BooleanField(default=False, verbose_name='принимать без проверки')),
                ('enabled', models.BooleanField(default=True, verbose_name='включено')),
                ('description', models.TextField(blank=True, verbose_name='обоснование')),
            ],
            options={
                'verbose_name': 'правило разметки',
                'verbose_name_plural': 'правила разметки',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='LearningSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_feedback', models.BooleanField(default=True, verbose_name='учитывать разметку диспетчеров')),
                ('retrain_weekly', models.BooleanField(default=True, verbose_name='переобучать раз в неделю')),
                ('auto_activate', models.BooleanField(default=True, help_text='новая версия заменяет действующую, только если не хуже неё на той же валидации', verbose_name='автоматически активировать лучшую версию')),
                ('retrain_on_degradation', models.BooleanField(default=False, verbose_name='переобучать при деградации')),
                ('degradation_ratio', models.FloatField(default=0.6, help_text='реализованная точность ниже этой доли от ожидаемой — тревога', verbose_name='порог деградации')),
                ('degradation_window_days', models.PositiveSmallIntegerField(default=14, verbose_name='окно контроля, сут')),
                ('degradation_min_resolved', models.PositiveSmallIntegerField(default=30, verbose_name='минимум прогнозов с исходом')),
                ('horizon_hours', models.PositiveSmallIntegerField(default=24, verbose_name='горизонт планового переобучения, ч')),
                ('last_check', models.JSONField(blank=True, default=dict, verbose_name='последняя проверка деградации')),
            ],
            options={
                'verbose_name': 'настройки дообучения',
                'verbose_name_plural': 'настройки дообучения',
            },
        ),
        migrations.CreateModel(
            name='FeedbackLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('task', models.CharField(choices=[('sensor_failure', 'Отказ датчика'), ('gas', 'Загазованность'), ('flood', 'Подтопление'), ('fire', 'Пожар'), ('intrusion', 'Несанкционированный доступ')], default='sensor_failure', max_length=32, verbose_name='задача')),
                ('label_date', models.DateField(db_index=True, verbose_name='дата события')),
                ('effect', models.CharField(choices=[('positive', 'Подтверждает отказ датчика'), ('negative', 'Не отказ датчика'), ('exclude', 'Исключить из обучения'), ('ignore', 'Не влияет на обучение')], max_length=16, verbose_name='эффект')),
                ('weight', models.FloatField(default=1.0, verbose_name='вес')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('accepted', 'Принята'), ('rejected', 'Отклонена')], db_index=True, default='pending', max_length=16, verbose_name='статус')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='проверено')),
                ('review_comment', models.CharField(blank=True, max_length=512, verbose_name='комментарий аналитика')),
                ('rows_affected', models.PositiveIntegerField(default=0, verbose_name='строк выборки изменено')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assets.channel', verbose_name='канал')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='диспетчер')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='incidents.decision', verbose_name='решение')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='incidents.incident', verbose_name='инцидент')),
                ('last_used_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='forecasting.mlmodel', verbose_name='учтена в модели')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='forecasting.prediction', verbose_name='прогноз')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='проверил')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecasting.feedbackrule', verbose_name='правило')),
            ],
            options={
                'verbose_name': 'метка обратной связи',
                'verbose_name_plural': 'метки обратной связи',
                'ordering': ('-created_at',),
                'permissions': [('review_feedback', 'Проверять разметку диспетчеров и управлять обучением')],
                'constraints': [models.UniqueConstraint(fields=('decision', 'channel'), name='uniq_label_per_decision_channel')],
            },
        ),
    ]
