# Generated by Django 5.2.17 on 2026-09-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0006_feedback_loop'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacklabel',
            name='source',
            field=models.CharField(choices=[('decision', 'Решение диспетчера'), ('emulated', 'Эмуляция для демонстрации')], default='decision', max_length=16, verbose_name='источник'),
        ),
    ]
