# Generated by Django 5.2.17 on 2026-09-23 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('forecasting', '0001_initial'),
        ('incidents', '0001_initial'),
        ('topology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('work_type', models.CharField(choices=[('inspection', 'Осмотр / проверка'), ('sensor_replacement', 'Замена датчика'), ('calibration', 'Калибровка / поверка'), ('power_check', 'Проверка электропитания'), ('pump_service', 'Обслуживание насосов'), ('ventilation', 'Обслуживание вентиляции'), ('cleaning', 'Очистка / откачка'), ('security', 'Проверка охраны периметра')], max_length=32, verbose_name='вид работ')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], max_length=16, verbose_name='приоритет')),
                ('due_date', models.DateField(verbose_name='рекомендуемый срок')),
                ('rationale', models.TextField(verbose_name='обоснование')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('done', 'Выполнена')], default='new', max_length=16, verbose_name='статус')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.channel', verbose_name='канал')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.equipment', verbose_name='оборудование')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='topology.node', verbose_name='объект')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecasting.prediction', verbose_name='прогноз')),
            ],
            options={
                'verbose_name': 'рекомендация по ТО',
                'verbose_name_plural': 'рекомендации по ТО',
                'ordering': ('due_date',),
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='номер')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждена'), ('submitted', 'Передана в систему заявок'), ('in_progress', 'В работе'), ('done', 'Выполнена'), ('cancelled', 'Отменена')], db_index=True, default='draft', max_length=16, verbose_name='статус')),
                ('work_type', models.CharField(choices=[('inspection', 'Осмотр / проверка'), ('sensor_replacement', 'Замена датчика'), ('calibration', 'Калибровка / поверка'), ('power_check', 'Проверка электропитания'), ('pump_service', 'Обслуживание насосов'), ('ventilation', 'Обслуживание вентиляции'), ('cleaning', 'Очистка / откачка'), ('security', 'Проверка охраны периметра')], max_length=32, verbose_name='вид работ')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], max_length=16, verbose_name='приоритет')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='описание и обоснование')),
                ('due_at', models.DateTimeField(verbose_name='срок выполнения')),
                ('external_id', models.CharField(blank=True, max_length=64, verbose_name='ID во внешней системе')),
                ('external_status', models.CharField(blank=True, max_length=64, verbose_name='статус во внешней системе')),
                ('external_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='синхронизировано')),
                ('report', models.TextField(blank=True, verbose_name='отчёт исполнителя')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='утвердил')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorders', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.equipment', verbose_name='оборудование')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorders', to='incidents.incident', verbose_name='инцидент')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workorders', to='topology.node', verbose_name='объект')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorders', to='workorders.maintenancerecommendation', verbose_name='рекомендация')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'ordering': ('-created_at',),
                'permissions': [('approve_workorder', 'Утверждать заявки'), ('execute_workorder', 'Исполнять заявки (бригада)')],
            },
        ),
    ]
