# Generated by Django 5.2.17 on 2026-09-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='external_assignee',
            field=models.CharField(blank=True, max_length=128, verbose_name='исполнитель во внешней системе'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='external_history',
            field=models.JSONField(blank=True, default=list, verbose_name='история во внешней системе'),
        ),
    ]
