# Generated by Django 5.2.17 on 2026-09-27 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_camera_equipment_condition_equipment_condition_at_and_more'),
        ('workorders', '0002_external_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ('-created_at',), 'permissions': [('approve_workorder', 'Утверждать заявки'), ('execute_workorder', 'Исполнять заявки (бригада)'), ('plan_maintenance', 'Планировать ТО: план работ, реестр оборудования, фактическое состояние')], 'verbose_name': 'заявка', 'verbose_name_plural': 'заявки'},
        ),
        migrations.CreateModel(
            name='EquipmentInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('inspected_at', models.DateTimeField(verbose_name='когда')),
                ('condition', models.CharField(choices=[('good', 'Исправно'), ('remarks', 'Работоспособно, есть замечания'), ('needs_repair', 'Требует ремонта'), ('faulty', 'Неисправно')], max_length=16, verbose_name='фактическое состояние')),
                ('maintenance', models.BooleanField(default=False, verbose_name='выполнено ТО')),
                ('notes', models.TextField(blank=True, verbose_name='замечания')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='assets.equipment', verbose_name='оборудование')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='кто')),
                ('workorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='workorders.workorder', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'осмотр оборудования',
                'verbose_name_plural': 'осмотры оборудования',
                'ordering': ('-inspected_at',),
            },
        ),
    ]
