# Generated by Django 5.2.17 on 2026-09-28 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0003_alter_node_options_node_adjacent_node_color_and_more'),
        ('workorders', '0003_alter_workorder_options_equipmentinspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('type_name', models.CharField(max_length=128, unique=True, verbose_name='вид оборудования')),
                ('system', models.CharField(blank=True, max_length=32, verbose_name='система')),
                ('unit', models.CharField(default='шт.', max_length=16, verbose_name='ед. изм.')),
                ('visits_per_year', models.PositiveSmallIntegerField(default=4, verbose_name='ТО в год')),
                ('repairs_per_year', models.PositiveSmallIntegerField(default=1, verbose_name='из них ТО+ТР')),
                ('ppr', models.BooleanField(default=False, verbose_name='ежегодный ППР и поверка')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='источник')),
            ],
            options={
                'verbose_name': 'регламент ТО',
                'verbose_name_plural': 'регламент ТО',
                'ordering': ('system', 'type_name'),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('kind', models.CharField(choices=[('to_tr', 'График ТО и ТР'), ('ppr', 'План-график ППР АКМ')], max_length=8, verbose_name='вид')),
                ('year', models.PositiveSmallIntegerField(verbose_name='год')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('source', models.CharField(choices=[('generated', 'Сформирован системой'), ('customer', 'Загружен из файла заказчика')], max_length=16, verbose_name='источник')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждён')], default='draft', max_length=16, verbose_name='статус')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='файл')),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='сводка')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='утвердил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='topology.node', verbose_name='зона')),
            ],
            options={
                'verbose_name': 'график работ',
                'verbose_name_plural': 'графики работ',
                'ordering': ('-year', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ScheduleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('object_label', models.CharField(max_length=255, verbose_name='объект (как в графике)')),
                ('type_name', models.CharField(blank=True, max_length=128, verbose_name='вид оборудования')),
                ('brand', models.CharField(blank=True, max_length=128, verbose_name='марка')),
                ('quantity', models.FloatField(default=0, verbose_name='количество')),
                ('unit', models.CharField(default='шт.', max_length=16, verbose_name='ед. изм.')),
                ('months', models.JSONField(blank=True, default=dict, verbose_name='отметки по месяцам')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='месяц ППР')),
                ('batch', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='партия ППР')),
                ('dismantle_on', models.DateField(blank=True, null=True, verbose_name='начало демонтажа')),
                ('delivery_on', models.DateField(blank=True, null=True, verbose_name='сдача в ОМ на ППР и поверку')),
                ('pickup_on', models.DateField(blank=True, null=True, verbose_name='вывоз из ОМ')),
                ('acceptance_on', models.DateField(blank=True, null=True, verbose_name='сдача работ комиссии')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='topology.node', verbose_name='объект')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='workorders.maintenanceschedule')),
            ],
            options={
                'verbose_name': 'строка графика',
                'verbose_name_plural': 'строки графика',
                'ordering': ('schedule', 'order'),
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='schedule_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorders', to='workorders.scheduleline', verbose_name='строка графика'),
        ),
    ]
