# Generated by Django 5.2.17 on 2026-09-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(unique=True, verbose_name='время')),
                ('temperature_c', models.FloatField(null=True, verbose_name='температура, °C')),
                ('humidity_pct', models.FloatField(null=True, verbose_name='влажность, %')),
                ('precipitation_mm', models.FloatField(null=True, verbose_name='осадки, мм')),
                ('snowfall_cm', models.FloatField(null=True, verbose_name='снег, см')),
                ('pressure_hpa', models.FloatField(null=True, verbose_name='давление, гПа')),
                ('is_forecast', models.BooleanField(default=False, verbose_name='прогноз')),
            ],
            options={
                'verbose_name': 'метеонаблюдение',
                'verbose_name_plural': 'метеоданные',
                'ordering': ('-ts',),
            },
        ),
    ]
