# Generated by Django 5.2.17 on 2026-09-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True, verbose_name='сутки')),
                ('precipitation_mm', models.FloatField(null=True, verbose_name='осадки, мм')),
                ('rain_mm', models.FloatField(null=True, verbose_name='дождь, мм')),
                ('snowfall_cm', models.FloatField(null=True, verbose_name='снег, см')),
                ('temperature_mean_c', models.FloatField(null=True, verbose_name='средняя температура, °C')),
                ('temperature_max_c', models.FloatField(null=True, verbose_name='максимальная температура, °C')),
                ('snow_depth_cm', models.FloatField(null=True, verbose_name='снежный покров, см')),
                ('is_forecast', models.BooleanField(default=False, verbose_name='прогноз')),
                ('source', models.CharField(default='open-meteo', max_length=32, verbose_name='источник')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'погода за сутки',
                'verbose_name_plural': 'погода по суткам',
                'ordering': ('-day',),
            },
        ),
    ]
