# Generated by Django 5.2.17 on 2026-09-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_weather_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='интеграция')),
                ('last_ok_at', models.DateTimeField(blank=True, null=True, verbose_name='последний успешный обмен')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='последняя ошибка')),
                ('last_error', models.TextField(blank=True, verbose_name='текст ошибки')),
                ('last_result', models.JSONField(blank=True, default=dict, verbose_name='итог последнего обмена')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'состояние интеграции',
                'verbose_name_plural': 'состояния интеграций',
                'permissions': [('manage_integrations', 'Проверять связь и запускать синхронизацию с внешними системами')],
            },
        ),
    ]
