# Generated by Django 5.2.17 on 2026-09-23 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('kind', models.CharField(choices=[('file', 'Файл (CSV/XLSX)'), ('stream', 'Поток (Kafka)'), ('api', 'REST API')], max_length=16, verbose_name='вид')),
                ('adapter', models.CharField(max_length=64, verbose_name='адаптер')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='настройки адаптера')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('read_only', models.BooleanField(default=True, editable=False, help_text='ТЗ §13: интеграция с системами заказчика исключительно в режиме read-only', verbose_name='только чтение')),
            ],
            options={
                'verbose_name': 'источник данных',
                'verbose_name_plural': 'источники данных',
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('file', models.FileField(blank=True, upload_to='imports/%Y/%m/', verbose_name='файл')),
                ('file_path', models.CharField(blank=True, max_length=512, verbose_name='путь к файлу на сервере')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='параметры')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Выполняется'), ('done', 'Завершён'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='статус')),
                ('rows_total', models.BigIntegerField(default=0, verbose_name='строк прочитано')),
                ('rows_ok', models.BigIntegerField(default=0, verbose_name='строк загружено')),
                ('rows_skipped', models.BigIntegerField(default=0, verbose_name='строк пропущено')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='начат')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='завершён')),
                ('error', models.TextField(blank=True, verbose_name='ошибка')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='инициатор')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='ingestion.datasource', verbose_name='источник')),
            ],
            options={
                'verbose_name': 'задание импорта',
                'verbose_name_plural': 'задания импорта',
                'ordering': ('-created_at',),
            },
        ),
    ]
