# Generated by Django 5.2.17 on 2026-09-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='quality',
            field=models.JSONField(blank=True, default=dict, verbose_name='качество данных'),
        ),
    ]
