# Generated by Django 5.2.17 on 2026-09-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_importjob_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='batch',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='пакет'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='kind',
            field=models.CharField(choices=[('history', 'Журнал за год (архив)'), ('window', 'Оперативное окно'), ('file', 'Загруженный файл')], default='file', max_length=16, verbose_name='вид'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='progress',
            field=models.FloatField(default=0, verbose_name='прогресс, %'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='stage',
            field=models.CharField(blank=True, max_length=128, verbose_name='этап'),
        ),
    ]
