# Generated by Django 5.2.17 on 2026-09-24 11:18

from django.db import migrations


def backfill(apps, schema_editor):
    # Задания импорта истории, созданные до появления поля kind, помечаются как годовые
    ImportJob = apps.get_model("ingestion", "ImportJob")
    ImportJob.objects.filter(source__code="smvu-archive", kind="file").update(kind="history")



class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_importjob_batch_importjob_kind_importjob_progress_and_more'),
    ]

    operations = [migrations.RunPython(backfill, migrations.RunPython.noop)]
