# Generated by Django 5.2.17 on 2026-09-28 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_history_kind_backfill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='format',
            field=models.CharField(blank=True, max_length=16, verbose_name='формат сообщения'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='sample',
            field=models.TextField(blank=True, verbose_name='пример сообщения'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='token',
            field=models.CharField(blank=True, max_length=64, verbose_name='ключ приёма'),
        ),
    ]
