# Generated by Django 5.2.17 on 2026-09-23 19:03

import apps.normalization.domain.engine
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('value_kind', models.CharField(choices=[(apps.normalization.domain.engine.ValueKind['NUMERIC'], apps.normalization.domain.engine.ValueKind['NUMERIC']), (apps.normalization.domain.engine.ValueKind['STATE'], apps.normalization.domain.engine.ValueKind['STATE']), (apps.normalization.domain.engine.ValueKind['MIXED'], apps.normalization.domain.engine.ValueKind['MIXED'])], max_length=16, verbose_name='тип значений')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name='единица измерения')),
                ('valid_min', models.FloatField(blank=True, null=True, verbose_name='мин. допустимое')),
                ('valid_max', models.FloatField(blank=True, null=True, verbose_name='макс. допустимое')),
                ('warn_threshold', models.FloatField(blank=True, null=True, verbose_name='порог предупреждения')),
                ('alarm_threshold', models.FloatField(blank=True, null=True, verbose_name='порог тревоги')),
                ('direction', models.CharField(choices=[('above', 'рост'), ('below', 'падение')], default='above', max_length=8, verbose_name='направление порога')),
                ('sentinels', models.JSONField(blank=True, default=list, verbose_name='служебные значения (= неисправность)')),
                ('expected_interval_s', models.PositiveIntegerField(default=3600, help_text='Для выявления «молчания» канала: отсутствие данных дольше N интервалов = подозрение на отказ', verbose_name='ожидаемый интервал между сообщениями, с')),
                ('silence_factor', models.PositiveSmallIntegerField(default=24, verbose_name='множитель молчания')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'профиль датчика',
                'verbose_name_plural': 'профили датчиков',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('pattern', models.CharField(max_length=255, verbose_name='значение / регулярное выражение')),
                ('is_regex', models.BooleanField(default=False, verbose_name='регулярное выражение')),
                ('state', models.CharField(choices=[(apps.normalization.domain.engine.State['NORMAL'], apps.normalization.domain.engine.State['NORMAL']), (apps.normalization.domain.engine.State['WARNING'], apps.normalization.domain.engine.State['WARNING']), (apps.normalization.domain.engine.State['ALARM'], apps.normalization.domain.engine.State['ALARM']), (apps.normalization.domain.engine.State['FAULT'], apps.normalization.domain.engine.State['FAULT']), (apps.normalization.domain.engine.State['POWER_LOSS'], apps.normalization.domain.engine.State['POWER_LOSS']), (apps.normalization.domain.engine.State['UNKNOWN'], apps.normalization.domain.engine.State['UNKNOWN']), (apps.normalization.domain.engine.State['EVENT'], apps.normalization.domain.engine.State['EVENT'])], max_length=16, verbose_name='каноническое состояние')),
                ('facet', models.CharField(default='primary', help_text='Составные устройства пишут несколько аспектов одновременно: основной, питание, охрана…', max_length=32, verbose_name='аспект')),
                ('priority', models.PositiveSmallIntegerField(default=100, verbose_name='приоритет')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='normalization.sensorprofile', verbose_name='профиль')),
            ],
            options={
                'verbose_name': 'правило состояния',
                'verbose_name_plural': 'правила состояний',
                'ordering': ('priority', 'id'),
            },
        ),
    ]
