# Generated by Django 5.2.17 on 2026-09-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staterule',
            name='guarded',
            field=models.BooleanField(default=False, help_text='Если источник не пометил событие тревожным, это рабочая активность, а не тревога', verbose_name='тревога только под охраной'),
        ),
    ]
