# Generated by Django 5.2.17 on 2026-09-24 10:17

from django.db import migrations, models


def set_gas_drift(apps, schema_editor):
    # Существующим стендам: профиль газа получает допуск дрейфа нуля, если он ещё не задан
    SensorProfile = apps.get_model("normalization", "SensorProfile")
    SensorProfile.objects.filter(code="gas_methane", drift_tolerance=None).update(drift_tolerance=0.1)



class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0002_staterule_guarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorprofile',
            name='drift_tolerance',
            field=models.FloatField(blank=True, help_text='Значения чуть ниже минимума считаются дрейфом (нужна калибровка), а не отказом', null=True, verbose_name='допуск дрейфа нуля'),
        ),
        migrations.RunPython(set_gas_drift, migrations.RunPython.noop),
    ]
